version: "3.7"
services:
    php-fpm:
        build:
            context: docker
            dockerfile: Dockerfile
            args:
                USER_ID: ${USER_ID}
                GROUP_ID: ${GROUP_ID}
                USER: ${USER}
                GROUP: ${GROUP}
                PHP_IMAGE: ${PHP_IMAGE}
        environment:
            PHP_IDE_CONFIG: serverName=localhost
        working_dir: /var/www
        volumes:
            - ../:/var/www:cached
            - ../.env:/var/www/.env:cached
    nginx:
        image: nginx:1.21.5-alpine
        working_dir: /var/www
        volumes:
            - ../public:/var/www/public:cached
            - ../.env:/var/www/.env:cached
            - ./host.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "127.0.0.1:80:80"
    mariadb:
        image: mariadb:10.7.3
        hostname: db
        environment:
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_USER: ${MARIADB_USER}
            MARIADB_PASSWORD: ${MARIADB_PASSWORD}
        volumes:
            - mariadb_data:/var/lib/mysql
    adminer:
        image: adminer
        ports:
            - 127.0.0.1:8080:8080
volumes:
    mariadb_data:
